import re
from tensorflow.python.platform import gfile

# Data format
#
# (A) data/tweets.txt
#   You have to parepare this file by yourself.
#   This file has many raw tweet and reply pairs. Odd lines are tweets and even lines are replies.
#   example)
#    Line 1: Hey how are you doing?
#    Line 2: @higepon doing good.
#
# Following files are generated by data_processer.py for training.
#
# (B) generated/tweets_enc.txt
#   Each lines consists of one tweet, @username and URL are removed.
#
# (C) generated/tweets_dec.txt
#   Each lines consists of one reply, @username and URL are removed.
#

DATA_DIR = "data"
GENERATED_DIR = "generated"
TWEETS_TXT = "{0}/tweets.txt".format(DATA_DIR)
TWEETS_ENC_TXT = "{0}/tweets_enc.txt".format(GENERATED_DIR)
TWEETS_DEC_TXT = "{0}/tweets_dec.txt".format(GENERATED_DIR)

def split_tweets_replies(tweets_path, enc_path, dec_path):
  """Read data from tweets_paths and split it to tweets and replies.

    Args:
      tweets_path: original tweets data
      enc_path: path to write tweets
      dec_path: path to write replies

    Returns:
      None
    """
  i = 1
  with gfile.GFile(tweets_path, mode="rb") as f, gfile.GFile(enc_path, mode="w") as ef, gfile.GFile(dec_path, mode="w") as df:
    for line in f:
      # Remove @username
      line = re.sub(r"@([A-Za-z0-9_]+)", "", line)
      # Remove URL
      line = re.sub(r'https?:\/\/.*', "", line)
      
      # Odd lines are tweets
      if i % 2 == 1:
        ef.write(line)
        # Even lines are replies
      else:
        df.write(line)
      i = i + 1

if __name__ == '__main__':
  print("Splitting to tweets and replies...")
  split_tweets_replies(TWEETS_TXT, TWEETS_ENC_TXT, TWEETS_DEC_TXT)
  print("Done")
